### ISSUE TITLE
Org-shiftup does not get logged. Why?

### ISSUE THREAD

**Issue by fniessen** [lewang/command-log-mode#2]
I'm trying to show what I type for updating an Org timestamp (S-up), but this does not get logged, though it's not part of the "exceptional" commands.

See http://screencast.com/t/rkBzDNyU, where I typed S-up twice...

Best regards

**Comment by pierre-rouleau** [comment]
Hello @fniessen .  I have tested your issue on [my fork of this package](https://github.com/pierre-rouleau/command-log-mode) and have not seen the issue. Do you still see the problem?  BTW, the link to your screencast is no longer valid (most probably due to time).

**Comment by fniessen** [comment]
Dear @pierre-rouleau , to be honest, I don't need this anymore ATM.  Would I need it again, for a video (for example), and would I encounter any problem, then I'd come back to you.

Thanks for your answer.
